# Generated by Django 4.2.7 on 2025-09-15 15:29

import apps.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moves', '0004_move_current_property_url_move_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('council', 'Council'), ('address_change', 'Address Change'), ('first_night', 'First Night'), ('utilities', 'Utilities'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('internet', 'Internet'), ('phone', 'Phone'), ('insurance', 'Insurance'), ('vehicles', 'Vehicles'), ('registration', 'Registration'), ('garage_sale', 'Garage Sale'), ('packing', 'Packing'), ('cleaning', 'Cleaning')], default='general', max_length=20)),
                ('location', models.CharField(choices=[('current', 'Current Address'), ('new', 'New Address'), ('utilities', 'Utilities'), ('vehicles', 'Vehicles'), ('garage_sale', 'Garage Sale')], default='current', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('time_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='moves.movecollaborator')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='moves.move')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-priority', 'due_date', 'created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('council', 'Council'), ('address_change', 'Address Change'), ('first_night', 'First Night'), ('utilities', 'Utilities'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('internet', 'Internet'), ('phone', 'Phone'), ('insurance', 'Insurance'), ('vehicles', 'Vehicles'), ('registration', 'Registration'), ('garage_sale', 'Garage Sale'), ('packing', 'Packing'), ('cleaning', 'Cleaning')], max_length=20)),
                ('location', models.CharField(choices=[('current', 'Current Address'), ('new', 'New Address'), ('utilities', 'Utilities'), ('vehicles', 'Vehicles'), ('garage_sale', 'Garage Sale')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_external', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'db_table': 'task_templates',
                'ordering': ['category', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Timer',
                'verbose_name_plural': 'Task Timers',
                'db_table': 'task_timers',
                'ordering': ['-created_at'],
            },
        ),
    ]
