# Generated by Django 4.2.7 on 2025-08-26 18:20

import apps.common.utils
import apps.common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move_date', models.DateField(validators=[apps.common.validators.validate_future_date])),
                ('current_location', models.TextField()),
                ('destination_location', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('office', 'Office'), ('storage', 'Storage'), ('other', 'Other')], max_length=20)),
                ('property_size', models.CharField(choices=[('studio', 'Studio'), ('1bedroom', '1 Bedroom'), ('2bedroom', '2 Bedroom'), ('3bedroom', '3 Bedroom'), ('4bedroom', '4+ Bedroom'), ('small_office', 'Small Office'), ('medium_office', 'Medium Office'), ('large_office', 'Large Office')], max_length=20)),
                ('special_items', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Moves',
                'db_table': 'moves',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
    ]
