# Generated by Django 4.2.7 on 2025-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='property_size',
            new_name='from_property_size',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='property_type',
            new_name='from_property_type',
        ),
        migrations.AddField(
            model_name='move',
            name='to_property_size',
            field=models.CharField(choices=[('studio', 'Studio'), ('1bedroom', '1 Bedroom'), ('2bedroom', '2 Bedroom'), ('3bedroom', '3 Bedroom'), ('4bedroom', '4+ Bedroom'), ('small_office', 'Small Office'), ('medium_office', 'Medium Office'), ('large_office', 'Large Office')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='to_property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('office', 'Office'), ('storage', 'Storage'), ('other', 'Other')], default='studio', max_length=20),
            preserve_default=False,
        ),
    ]
