# Generated by Django 4.2.7 on 2025-08-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_rename_property_size_move_from_property_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='from_property_size',
        ),
        migrations.RemoveField(
            model_name='move',
            name='to_property_size',
        ),
    ]
