# Generated by Django 4.2.7 on 2025-09-10 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0003_remove_move_from_property_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='current_property_url',
            field=models.URLField(blank=True, help_text='URL from Domain.com.au or Realestate.com.au', null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='move',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('first_home_buyer', 'First Home Buyer'), ('seniors', 'Seniors Discount'), ('single_parent', 'Single Parent')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='move',
            name='new_property_url',
            field=models.URLField(blank=True, help_text='URL from Domain.com.au or Realestate.com.au', null=True),
        ),
        migrations.CreateModel(
            name='MoveCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('owner', 'Move Owner'), ('family', 'Family Member'), ('friend', 'Friend'), ('helper', 'Helper')], default='helper', max_length=20)),
                ('permissions', models.CharField(choices=[('view_tasks', 'View Tasks Only'), ('edit_tasks', 'Edit Tasks'), ('full_access', 'Full Access (No Budget)')], default='view_tasks', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='moves.move')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Move Collaborator',
                'verbose_name_plural': 'Move Collaborators',
                'db_table': 'move_collaborators',
                'unique_together': {('move', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='moves.movecollaborator')),
                ('timeline_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timeline.timelineevent')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'db_table': 'task_assignments',
                'unique_together': {('timeline_event', 'collaborator')},
            },
        ),
    ]
