# Generated by Django 5.2.7 on 2025-10-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0004_move_current_property_url_move_discount_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="move",
            name="current_property_url",
        ),
        migrations.RemoveField(
            model_name="move",
            name="new_property_url",
        ),
        migrations.AddField(
            model_name="move",
            name="current_property_floor_map",
            field=models.ImageField(
                blank=True,
                help_text="Floor map of current property",
                null=True,
                upload_to="property_floor_maps/",
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="new_property_floor_map",
            field=models.ImageField(
                blank=True,
                help_text="Floor map of new property",
                null=True,
                upload_to="property_floor_maps/",
            ),
        ),
    ]
