# Generated by Django 5.2.5 on 2025-11-22 15:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0006_move_estimated_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="move",
            name="estimated_budget",
        ),
        migrations.CreateModel(
            name="MoveExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("moving_company", "Moving Company"),
                            ("packing_supplies", "Packing Supplies"),
                            ("storage", "Storage"),
                            ("utilities", "Utilities Setup"),
                            ("cleaning", "Cleaning Services"),
                            ("insurance", "Insurance"),
                            ("transportation", "Transportation"),
                            ("food", "Food & Meals"),
                            ("accommodation", "Accommodation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "receipt",
                    models.ImageField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="moves.move",
                    ),
                ),
            ],
            options={
                "verbose_name": "Move Expense",
                "verbose_name_plural": "Move Expenses",
                "db_table": "move_expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
    ]
