# Generated by Django 5.2.5 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0007_remove_move_estimated_budget_moveexpense"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="estimated_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated moving budget",
                max_digits=10,
                null=True,
            ),
        ),
    ]
