# Generated by Django 4.2.7 on 2025-09-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_1', models.FileField(upload_to='partner_documents/')),
                ('document_2', models.FileField(upload_to='partner_documents/')),
                ('document_3', models.FileField(upload_to='partner_documents/')),
                ('document_4', models.FileField(upload_to='partner_documents/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Document',
                'verbose_name_plural': 'Partner Documents',
                'db_table': 'partner_documents',
            },
        ),
    ]
