# Generated by Django 4.2.7 on 2025-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdocument',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='partner_documents/'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='partner_documents/'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='partner_documents/'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='document_4',
            field=models.FileField(blank=True, null=True, upload_to='partner_documents/'),
        ),
    ]
