# Generated by Django 4.2.7 on 2025-08-26 18:20

import apps.common.utils
import apps.common.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('garage', 'Garage'), ('basement', 'Basement'), ('attic', 'Attic'), ('other', 'Other')], max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('boxes', models.IntegerField(default=0)),
                ('heavy_items', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', validators=[apps.common.validators.validate_image_file])),
                ('packed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rooms', to='moves.move')),
            ],
            options={
                'verbose_name': 'Inventory Room',
                'verbose_name_plural': 'Inventory Rooms',
                'db_table': 'inventory_rooms',
                'ordering': ['created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
    ]
