# Generated by Django 4.2.7 on 2025-09-15 15:31

import apps.common.utils
import apps.common.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_move_current_property_url_move_discount_percentage_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_details', models.TextField(blank=True, null=True)),
                ('storage_unit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='storage_contracts/')),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='moves.move')),
            ],
            options={
                'verbose_name': 'Storage Item',
                'verbose_name_plural': 'Storage Items',
                'db_table': 'storage_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('small', 'Small Box'), ('medium', 'Medium Box'), ('large', 'Large / Tea Chest Box'), ('extra_large', 'Extra Large'), ('book_wine', 'Book/Wine Carton'), ('picture_mirror', 'Picture/Mirror Box'), ('port_a_robe', 'Port-a-Robe Carton'), ('tv_carton', 'TV Carton'), ('dish_glassware', 'Dish/Glassware Box'), ('audio_file', 'Audio / File Box'), ('mattress', 'Mattress Box')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('contents', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('fragile', models.BooleanField(default=False)),
                ('packed', models.BooleanField(default=False)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='box_images/', validators=[apps.common.validators.validate_image_file])),
                ('destination_room', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_boxes', to='moves.move')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes_in_room', to='inventory.inventoryroom')),
            ],
            options={
                'verbose_name': 'Inventory Box',
                'verbose_name_plural': 'Inventory Boxes',
                'db_table': 'inventory_boxes',
                'ordering': ['created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='HighValueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fine_art', 'Fine art/paintings'), ('antiques', 'Antiques'), ('designer_furniture', 'Designer furniture'), ('collectibles', 'Collectibles (e.g., rare books, coins)')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('insured', models.BooleanField(default=False)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_value_items', to='moves.move')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_value_items_in_room', to='inventory.inventoryroom')),
            ],
            options={
                'verbose_name': 'High Value Item',
                'verbose_name_plural': 'High Value Items',
                'db_table': 'high_value_items',
                'ordering': ['created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='HeavyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('piano', 'Pianos'), ('pool_table', 'Pool tables'), ('sculpture', 'Large sculptures/statues'), ('aquarium', 'Aquariums'), ('gym_equipment', 'Home gym equipment')], max_length=20)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requires_special_handling', models.BooleanField(default=True)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='heavy_item_images/', validators=[apps.common.validators.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heavy_items', to='moves.move')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heavy_items_in_room', to='inventory.inventoryroom')),
            ],
            options={
                'verbose_name': 'Heavy Item',
                'verbose_name_plural': 'Heavy Items',
                'db_table': 'heavy_items',
                'ordering': ['created_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
    ]
