# Generated by Django 4.2.7 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storageitem_inventorybox_highvalueitem_heavyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='access_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='category',
            field=models.CharField(choices=[('self_storage', 'Self Storage'), ('warehouse', 'Warehouse'), ('climate_controlled', 'Climate Controlled'), ('document_storage', 'Document Storage'), ('other', 'Other')], default='self_storage', max_length=20),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='monthly_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
