# Generated by Django 4.2.7 on 2025-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storageitem_access_details_storageitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='name',
            field=models.CharField(default='Storage Item', max_length=200),
        ),
    ]
