# Generated by Django 5.2.5 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventoryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
