# Generated by Django 4.2.7 on 2025-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_unique_together_booking_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
