# Generated by Django 4.2.7 on 2025-09-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='google_event_id',
            new_name='google_calendar_event_id',
        ),
    ]
