# Generated by Django 4.2.7 on 2025-08-26 18:20

import apps.common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'db_table': 'checklist_templates',
                'ordering': ['-week', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('days_from_move', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('logistics', 'Logistics'), ('preparation', 'Preparation'), ('supplies', 'Supplies'), ('utilities', 'Utilities'), ('address_change', 'Address Change'), ('packing', 'Packing'), ('moving_day', 'Moving Day')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('estimated_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='moves.move')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'timeline_events',
                'ordering': ['days_from_move', 'priority'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='moves.move')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'db_table': 'checklist_items',
                'ordering': ['-week', 'priority', 'title'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
    ]
