# Generated by Django 4.2.7 on 2025-08-26 18:23

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
    ]
