# Generated by Django 4.2.7 on 2025-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
