# Generated by Django 4.2.7 on 2025-09-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doucment_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
