# Generated by Django 4.2.7 on 2025-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_document_verified_user_is_doucment_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_changes_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pricing_plan',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plan +'), ('concierge', 'Concierge +')], default='free', max_length=20),
        ),
    ]
