# Generated by Django 4.2.7 on 2025-09-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_date_changes_used_user_pricing_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
