# Generated by Django 4.2.7 on 2025-08-26 18:20

import apps.common.utils
import apps.common.validators
import apps.files.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.floor_plan_upload_path, validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_document_file])),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('location_type', models.CharField(choices=[('current', 'Current Location'), ('new', 'New Location')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='moves.move')),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'verbose_name_plural': 'Floor Plans',
                'db_table': 'floor_plans',
                'ordering': ['-uploaded_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.document_upload_path, validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_document_file])),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('inventory', 'Inventory'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='moves.move')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
            bases=(models.Model, apps.common.utils.ChoicesMixin),
        ),
    ]
